### ISSUE TITLE
Incorrect fulfillment acceptance rate

### ISSUE THREAD

**Issue by b-mueller** [Bounties-Network/Explorer#288]
Hi guys, not sure if this is the best place to report this but here it goes.

I noticed that the fulfillment acceptance rate show on my [profile page](https://explorer.bounties.network/profile/0x0583858adfe7d1d3dc7f8447301cf7b7b056d638/) is 27%. AFAIK all bounties have been fulfilled so I this this should show 100%.

Perhaps this has to do with the fact that 7/8 bounties originate from Gitcoin? Does Bounties Network pick those up automatically?

**Comment by mbeylin** [comment]
Hey Bernhard, I believe the stat is accurate but is outdated based on the way you're using bounties right now. I assume because you had one bounty which had many submissions (of which not all were accepted), the statistic got skewed. We'll be changing these reputational metrics soon to reflect updated user patterns.

**Comment by b-mueller** [comment]
Ohh, ok. I misinterpreted how this works then.

**Comment by c-o-l-o-r** [comment]
Thanks for issue @b-mueller, we've updated the calculation in this PR: https://github.com/Bounties-Network/BountiesAPI/pull/253 

You should see it rolled out sometime today 😄
